apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: y6fze139y-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1726bcbb9f.tqau.p3.openshiftapps.com/rhtap/rhtap-qe-go:179a0a8dc9cbdb29c6148842c2a73320a004c9a1@sha256:675a38b5e38a69bd80222ac00d5931f61a3227cc9218d30575499e9a32d7c0b2
          name: container-image
